name: Job Container Practice

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4

      - run: node --version

      - run: npm --version

      - run: ls -la