name: Job Container Practice

on:
  workflow_dispatch:
  push:
    branches:
       - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: node:20

    services:
      mongodb:
        image: mongo:7

        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - run: node --version

      - run: npm --version

      - run: ls -la